name: Binder Container Image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v4

    - name: Build & push Binder container + cache
      uses: jupyterhub/repo2docker-action@master
      with:
        IMAGE_NAME: docker.io/rcdpge/capstone-binder:${{ github.sha }}
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        BINDER_CACHE: true
        MYBINDERORG_TAG: true
