name: Binder Container Image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  packages: write 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set SHA encryption
      id: shortsha
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - uses: jupyterhub/repo2docker-action@master
      with:
        IMAGE_NAME: ghcr.io/rcdpge/capstone-binder:${{ steps.shortsha.outputs.SHORT_SHA }}
        BINDER_CACHE: true
        MYBINDERORG_TAG: true
        LATEST_TAG_OFF: true
