name: Update Pip Badge
on: [push, pull_request]

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Generate pip badge
      uses: tj-actions/pip-version@v1
      with:
        badge_path: assets/pip-version.svg
        left_text: pip
        left_color: grey
        right_color: green
        link: https://pypi.org/project/pip/
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Update pip badge [skip ci]'
        file_pattern: assets/pip-version.svg
